languageCode: cn
title: iResty
theme: hugo-fresh-859e3d2
publishDir: docs
baseURL: https://iresty.github.io/
blackfriday:
  hrefTargetBlank: true
# disableKinds:
#   - "taxonomy"
#   - "taxonomyTerm"
params:
  navbarlogo:
  # Logo (from /images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: 微服务 API 管理平台
    # Hero subtitle (optional)
    subtitle: 支持多云和混合云环境，连接您所有 API 和微服务到开源、极致性能、注重安全和可扩展的平台
    # Button text
    buttontext: 免费试用
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: 开源项目
    url: https://github.com/iresty
  - title: 产品功能
    url: /
  - title: 免费试用
    url: /
  - title: 关于我们
    url: /
    # sublinks:
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: 我们的优势体现在
    subtitle: 背后是开发者驱动的开源社区
    tiles:
    - title: 极致性能
      icon: mouse-globe
      text: 毫秒级延时，单机 4 万 QPS，路由性能超出同类产品 10 倍
      url: /
      buttonText: 性能白皮书

    - title: 没有绑定
      icon: laptop-cloud
      text: 支持多云和混合云，灵活弹性伸缩；开源，不锁定用户
      url: /
      buttonText: 免费试用

    - title: 热加载
      icon: plug-cloud
      text: 函数和插件热加载机制，更适合 Serverless 和 IoT
      url: /
      buttonText: 查看文档

  section2:
    title: 用最好的 API 网关助力业务发展
    subtitle: 我们提供您需要的一切
    features:
    - title: 易用的管理界面，强大的开发接口
      text: 开源版本中自带简洁、易用的管理界面，并提供强大、灵活的接口以便开发者使用。
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: 高可用，安全第一
      text: 内置高可用方案，并提供多种身份认证和接口校验的安全插件，把稳定和安全放在第一位。
      icon: doc-sync
    - title: 私有部署，自定义插件
      text: 支持部署在私有网络中，可以根据业务需求开发自己的私有插件。
      icon: mobile-feed
  section3:
    title: 运维可视化大屏
    subtitle: 掌控业务运行数据
    image: illustrations/mockups/app-mockup.png
    buttonText: 在线演示版本
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/iresty
      # Icons are from Font Awesome
      icon: github
    - link: https://twitter.com/
      icon: twitter
    - link: https://weibo.com/
      icon: weibo
    - link: https://wechat.com/
      icon: wechat


    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: Request features
          link: /
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /
        - text: Tech articles
          link: /
        - text: Video blog
          link: /
