languageCode: cn
title: iResty
theme: hugo-fresh-859e3d2
publishDir: docs
baseURL: https://www.iresty.com/
blackfriday:
  hrefTargetBlank: true
# disableKinds:
#   - "taxonomy"
#   - "taxonomyTerm"
params:
  navbarlogo:
  # Logo (from /images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: 微服务 API 管理平台
    # Hero subtitle (optional)
    subtitle: 为您的所有 API 和微服务提供极致性能、注重安全、开源和可扩展的平台; 并提供 API 网关以及周边的商业支持
    # Button text
    buttontext: 立即联系我们
    # Where the main hero button links to
    buttonlink: "mailto:ming@iresty.com"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: GitHub
    url: https://github.com/iresty
  - title: 产品功能
    url: https://github.com/iresty/apisix/blob/master/README_CN.md#%E5%8A%9F%E8%83%BD
  - title: 立即开始
    url: http://apisix.iresty.com
  - title: 关于我们
    url: /
    # sublinks:
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: 我们的优势
    subtitle: 活跃的开源社区，真实使用场景驱动
    tiles:
    - title: 极致性能
      icon: mouse-globe
      text: 微秒级延时，单机 6 万 QPS，路由性能超出同类产品 10 倍
      url: https://www.iresty.com/download/%E4%BC%81%E4%B8%9A%E7%94%A8%E6%88%B7%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E5%BE%AE%E6%9C%8D%E5%8A%A1%20API%20%E7%BD%91%E5%85%B3.pdf
      buttonText: 产品白皮书

    - title: 没有绑定
      icon: laptop-cloud
      text: 支持多云（混合云），灵活弹性伸缩；开源，不锁定用户
      url: https://github.com/iresty/apisix#who-uses-apisix
      buttonText: 这些公司都在使用

    - title: 热加载
      icon: plug-cloud
      text: 函数和插件热加载机制，更适合 Serverless 和 IoT
      url: https://github.com/iresty/apisix/blob/master/README_CN.md#%E5%8A%9F%E8%83%BD
      buttonText: 了解更多功能

  section2:
    title: 提供 API 网关以及周边的商业支持
    subtitle: 由开源项目的核心开发成员组成
    features:
    - title: 易用的管理界面，强大的开发接口
      text: 开源版本中自带简洁、易用的管理界面，并提供强大、灵活的接口以便开发者使用。
      icon: laptop-globe
    - title: 高可用，安全第一
      text: 内置高可用方案，并提供多种身份认证和接口校验的安全插件，把稳定和安全放在第一位。
      icon: doc-sync
    - title: 私有部署，自定义插件
      text: 支持部署在私有网络中，可以根据业务需求开发自己的私有插件。
      icon: mobile-feed
  section3:
    title: 运维可视化大屏
    subtitle: 掌控业务运行数据
    image: illustrations/mockups/app-mockup.png
    buttonText: 在线演示版本
    buttonLink: "http://apisix.iresty.com"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/iresty
      icon: github
    - link: https://twitter.com/apisixfast
      icon: twitter
    - link: https://mp.weixin.qq.com/s/VpKPY4mbFql3N7BAbcvUHQ
      icon: wechat


    bulmalogo: true
    quicklinks:
      column1:
        title: "产品"
        links:
        - text: APISIX 的用户有哪些？
          link: https://github.com/iresty/apisix#who-uses-apisix
        - text: 路线图
          link: https://github.com/iresty/apisix/milestones
      column2:
        title: "文档"
        links:
        - text: 功能列表
          link: https://github.com/iresty/apisix/blob/master/README_CN.md#%E5%8A%9F%E8%83%BD
        - text: 快速入门
          link: https://github.com/iresty/apisix/blob/master/README_CN.md#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B
        - text: 常见问题
          link: https://github.com/iresty/apisix/blob/master/FAQ_CN.md
      column3:
        title: "资源"
        links:
        - text: 知乎专栏
          link: https://zhuanlan.zhihu.com/p/81306020
        - text: GitHub
          link: https://github.com/iresty

